# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProcesHidric
                                 A QGIS plugin
 Este plugin procesa la red hidrica de un departamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-08-25
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Isabel Fuentes
        email                : isabelfuentes@unah.hn
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

#Initialize Qt resources from file resources.py
from .resources import *

#Importa el codigo del dialogo
from.ClipTool_dialog import  ClipToolDialog
import os.path


# Importar módulos de geoprocesos de QGIS
from qgis.core import QgsProject, QgsVectorLayer
from qgis.analysis import QgsNativeAlgorithms
from qgis.utils import iface

# Importar y configurar el procesamiento
import processing
from processing.core.Processing import Processing

# Import the code for the dialog
from .geoproceso_dialog import GeoprocesoDialog

#Inicializar el entorno de procesamiento de QGIS
Processing.initialize()

class ProcesHidric:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ProcesHidric_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Procesos de Red Hidrica')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ProcesHidric', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/proceshidric/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'ProcesHidric'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Procesos de Red Hidrica'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ProcesHidricDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:


       
       #Obtener las rutas de archivo desde el diálogo
      
       inputFile = self.dlg.capaentrada.filePath()
       print(f"capa entrada = {inputFile}")

       clipRios = self.dlg.capacorte.filePath()
       print(f"rios cortados = {clipFile}")

       TEMPORARY_OUTPUT = self.dlg.capacorte.filePath()
       print(f"capa salida = {TEMPORARY_OUTPUT}")

       print("\nComenzando Geoproceso...")

       rioscorte = processing.runAndLoadResults("native:clip", {'INPUT': inputFile,'OVERLAY':clipFile,'OUTPUT':TEMPORARY_OUTPUT})
            
       
       Rios1  =  iface . addVectorLayer ( clipRios [ 'OUTPUT' ],  "Red Hidrica Primaria" ,  "ogr" )
       Rios1 .setSubsetString ( " Codigo = 1" )
​
       Rios2  =  iface . addVectorLayer ( clipRios [ 'OUTPUT' ],  "Red Hidráulica Secundaria" ,  "ogr" )
       Rios2 .setSubsetString ( " Codigo = 2" )
​
       Rios3  =  iface . addVectorLayer ( clipRios [ 'OUTPUT' ],  "Red Hidrica Terciaria" ,  "ogr" )
       Rios3 .setSubsetString ( " Codigo = 3" )
​
       buffRios1 = processing.runAndLoadResults("native:buffer", {'INPUT':Rios1,
                                                           'DISTANCE':100,'SEGMENTS':5,'END_CAP_STYLE':0,
                                                           'JOIN_STYLE':0,'MITER_LIMIT':2,'DISSOLVE':True,
                                                           'OUTPUT':TEMPORARY_OUTPUT})

       buffRios2 = processing.runAndLoadResults("native:buffer", {'INPUT':Rios2,'DISTANCE':50,'SEGMENTS':5,'END_CAP_STYLE':0,
                                                           'JOIN_STYLE':0,'MITER_LIMIT':2,'DISSOLVE':True,
                                                           'OUTPUT':TEMPORARY_OUTPUT})
                 
      buffRios3 = processing.runAndLoadResults("native:buffer", {'INPUT':Rios3,'DISTANCE':20,'SEGMENTS':5,'END_CAP_STYLE':0,
                                                           'JOIN_STYLE':0,'MITER_LIMIT':2,'DISSOLVE':True,
                                                           'OUTPUT':TEMPORARY_OUTPUT})
      
     print("\nGeoproceso Finalizado")
            
       
